//
// Created by 薛轲翰 on 2020/6/26.
//

#ifndef MJAVA_COMPILER_PARSER_PARSER_SYNTAX_TREE_NODE_H_
#define MJAVA_COMPILER_PARSER_PARSER_SYNTAX_TREE_NODE_H_

class SyntaxTreeNode {

};

#endif //MJAVA_COMPILER_PARSER_PARSER_SYNTAX_TREE_NODE_H_
